package core

import (
	"bufio"
	"encoding/hex"
	"math"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

// The fixtures are generated by scripts/mkfixture.py from the captured tapes
// plus every 4-decimal string landing on a half-cent. Each row pins what
// CPython produced, including the raw float64 bits of the intermediate product,
// so a Go implementation that passes has the same primitive rather than merely
// the same answers on today's sample.

func fixture(t *testing.T, name string) [][]string {
	t.Helper()
	path := filepath.Join("..", "..", "testdata", name)
	fh, err := os.Open(path)
	if err != nil {
		t.Fatalf("open fixture: %v", err)
	}
	t.Cleanup(func() { fh.Close() })

	var rows [][]string
	sc := bufio.NewScanner(fh)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	for sc.Scan() {
		line := sc.Text()
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		rows = append(rows, strings.Split(line, "\t"))
	}
	if err := sc.Err(); err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	if len(rows) == 0 {
		t.Fatalf("fixture %s is empty", path)
	}
	return rows
}

func TestParsePriceCentsMatchesCPython(t *testing.T) {
	rows := fixture(t, "prices.tsv")
	for _, r := range rows {
		s, wantCents, wantBits := r[0], r[1], r[2]

		got, err := ParsePriceCents(s)
		if err != nil {
			t.Fatalf("%q: %v", s, err)
		}
		want, err := strconv.Atoi(wantCents)
		if err != nil {
			t.Fatalf("bad fixture row %v: %v", r, err)
		}
		if got != want {
			t.Errorf("ParsePriceCents(%q) = %d, CPython round() = %d", s, got, want)
		}

		// Also pin the intermediate: if the product's bits differ, the two
		// implementations agree here only by luck.
		f, _ := strconv.ParseFloat(s, 64)
		bits := make([]byte, 8)
		u := math.Float64bits(f * 100)
		for i := 0; i < 8; i++ {
			bits[i] = byte(u >> (56 - 8*i))
		}
		if h := hex.EncodeToString(bits); h != wantBits {
			t.Errorf("%q: product bits %s, CPython %s", s, h, wantBits)
		}
	}
	t.Logf("%d price strings match CPython exactly", len(rows))
}

// The fixture is only worth running if it actually discriminates the two
// rounding modes. If a future change to the generator drops the half-cent
// cases, this fails loudly rather than passing vacuously.
func TestFixtureDiscriminatesBankersRounding(t *testing.T) {
	rows := fixture(t, "prices.tsv")
	n := 0
	for _, r := range rows {
		f, _ := strconv.ParseFloat(r[0], 64)
		if int(math.Round(f*100)) != int(math.RoundToEven(f*100)) {
			n++
		}
	}
	if n == 0 {
		t.Fatal("fixture contains no case where math.Round differs from " +
			"math.RoundToEven; it cannot detect the banker's-rounding hazard")
	}
	t.Logf("%d of %d price strings expose the banker's-rounding hazard", n, len(rows))
}

func TestParseSizeMatchesCPython(t *testing.T) {
	rows := fixture(t, "sizes.tsv")
	for _, r := range rows {
		got, err := ParseSize(r[0])
		if err != nil {
			t.Fatalf("%q: %v", r[0], err)
		}
		want, err := hex.DecodeString(r[1])
		if err != nil || len(want) != 8 {
			t.Fatalf("bad fixture row %v", r)
		}
		var u uint64
		for _, b := range want {
			u = u<<8 | uint64(b)
		}
		if math.Float64bits(got) != u {
			t.Errorf("ParseSize(%q) = %v (bits %016x), CPython bits %016x",
				r[0], got, math.Float64bits(got), u)
		}
	}
	t.Logf("%d size strings match CPython exactly", len(rows))
}
