package main
import("context";"encoding/json";"fmt";"net/http";"os";"sync";"time";"lip/feed";"lip/harness/cfg";"lip/harness/wsx")
type record struct {UTC string `json:"utc"`; Event string `json:"event"`; Connection int `json:"connection,omitempty"`; SID int64 `json:"sid,omitempty"`; Code int `json:"code,omitempty"`}
type log struct{mu sync.Mutex; rows []record}
func(l *log)add(e string,g int,s int64,c int){l.mu.Lock(); defer l.mu.Unlock(); l.rows=append(l.rows,record{time.Now().UTC().Format(time.RFC3339Nano),e,g,s,c})}
type socket struct {wsx.Socket; l *log}
func(s *socket)Write(c context.Context,b []byte)error{var m struct{Cmd string `json:"cmd"`; Params struct{Channels []string `json:"channels"`; Action string `json:"action"`; Sids []int64 `json:"sids"`} `json:"params"`}; if json.Unmarshal(b,&m)!=nil{return fmt.Errorf("malformed request")}; switch m.Cmd{case "subscribe":for _,ch:=range m.Params.Channels{if ch!="orderbook_delta"&&ch!="trade"{return fmt.Errorf("channel refused")}};case "update_subscription":if m.Params.Action!="get_snapshot"||len(m.Params.Sids)!=1{return fmt.Errorf("non-data request refused")};s.l.add("get_snapshot_wire",0,m.Params.Sids[0],0);default:return fmt.Errorf("non-data request refused")};return s.Socket.Write(c,b)}
type dialer struct{next wsx.Dialer; sockets chan wsx.Socket;l *log}
func(d dialer)Dial(c context.Context,u string,h http.Header)(wsx.Socket,error){s,e:=d.next.Dial(c,u,h);if e!=nil{return nil,e};w:=&socket{s,d.l};d.sockets<-w;return w,nil}
func main(){l:=&log{};s,e:=feed.NewSigner();if e!=nil{fmt.Println("credential initialization failed");os.Exit(1)};d:=dialer{wsx.NewLiveDialer(),make(chan wsx.Socket,4),l};sup,e:=wsx.NewSupervisor(s,d,wsx.NewSystemClock(),cfg.Default(),[]string{"KXTOKENUSE-26SEP28-T146"});if e!=nil{fmt.Println("supervisor initialization failed");os.Exit(1)};ctx,cancel:=context.WithTimeout(context.Background(),45*time.Second);cmds:=make(chan wsx.Command,4);events:=make(chan wsx.Event,256);done:=make(chan struct{});go func(){_ =sup.Run(ctx,cmds,events);close(done)}();g,initial,resnap,disconnected:=0,0,0,0;var sid int64;var current wsx.Socket; requested:=false;success:=false
loop:for {select{case <-ctx.Done():break loop;case ev:=<-events:switch ev.Kind{case wsx.EventConnected:g++;sid=0;initial=0;requested=false;current=<-d.sockets;l.add("connected",g,0,0);case wsx.EventDisconnected:disconnected++;l.add("disconnected",g,0,0);case wsx.EventFrame:info:=wsx.InspectFrame(ev.Frame);if info.BookSubscribeSID!=nil{sid=*info.BookSubscribeSID;l.add("book_subscribed",g,sid,0)};if info.Kind==wsx.FrameError{var x struct{Msg struct{Code int `json:"code"`} `json:"msg"`};_ =json.Unmarshal(ev.Frame,&x);l.add("error_frame",g,0,x.Msg.Code);break loop};if info.Kind==wsx.FrameSnapshot&&info.Deliver&&info.Ticker=="KXTOKENUSE-26SEP28-T146"{initial++;l.add("snapshot",g,sid,0);if initial==1&&sid>0{cmds<-wsx.Command{Kind:wsx.CmdResnapshot,Sids:[]int64{sid},Tickers:[]string{info.Ticker}};requested=true}else if initial==2&&requested{resnap++;if g==1{l.add("forced_socket_close",g,sid,0);_ =current.Close()}else if g==2&&disconnected>=1&&resnap==2{success=true;break loop}}}}}}
cancel();select{case <-done:case <-time.After(3*time.Second):};l.mu.Lock();b,_:=json.MarshalIndent(map[string]any{"success":success,"connections":g,"disconnects":disconnected,"requested_snapshots_received":resnap,"scope":"Production websocket supervisor/session data subscription and snapshot protocol only; not the full owner/portfolio process and not q01 qualification.","financial_requests":0,"events":l.rows},"","  ");l.mu.Unlock();if os.WriteFile("/private/tmp/lip-ws-protocol-evidence.json",append(b,'\n'),0600)!=nil{os.Exit(1)};if !success{os.Exit(1)}}
